import { serverEnv } from '@/lib/env/server'
import { fileURLToPath } from 'bun'
import { existsSync } from 'node:fs'
import fs from 'node:fs/promises'
import path from 'node:path'
import openApiTS, { astToString } from 'openapi-typescript'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const outputPath = path.resolve(__dirname, '../types/chatterbox-api.d.ts')

const main = async () => {
  const apiUrl = serverEnv.CHATTERBOX_API_URL
  const openAPIUrl = `${apiUrl}/openapi.json`
  console.log(`Fetching OpenAPI spec from ${openAPIUrl}...`)
  const ast = await openApiTS(new URL(openAPIUrl))
  const content = astToString(ast)

  const outputDir = path.dirname(outputPath)
  if (existsSync(outputDir)) {
    await fs.mkdir(outputDir, { recursive: true })
  }
  const header = `/**
  * This file is auto-generated by scripts/sync-api.ts
  * Do not edit this file manually. Run "bun run sync-api" to regenerate it.
  *
  * Generated from OpenAPI spec at ${openAPIUrl}
  * Generation timestamp: ${new Date().toISOString()}
  */\n\n`
  await fs.writeFile(outputPath, header + content)
  console.log(`Type definitions written to ${outputPath}`)
}

main().catch((error) => {
  console.error('Error generating API types:', error)
  process.exit(1)
})
